"""
Execution Syntax:
Run this script from the root terminal:
python -m app.database.populate
"""

from app import app, db  # imports Flask app & SQLAlchemy db from init.py
from app.database.model import Utilisateur, Produit, Commande, LigneCommande
from werkzeug.security import generate_password_hash
import random
from faker import Faker  # generate realistic fake data

# Set number of records per table
NUM_RECORDS = 30

# Initialize Faker with French locale for realistic French names/addresses
fake = Faker("fr_FR")


def seed_database():
    """
    Cleans the database and populates it with realistic IT
    product data and users.
    Restores specific hardware categories to ensure believable product names.
    """
    with app.app_context():
        print("Cleaning up the database...")
        # Delete records in reverse order of dependencies
        # to avoid Foreign Key constraints
        db.session.query(LigneCommande).delete()
        db.session.query(Commande).delete()
        db.session.query(Produit).delete()
        db.session.query(Utilisateur).delete()

        # 1. Generate Users
        print("Generating users...")
        utilisateurs = []
        for _ in range(NUM_RECORDS):
            user = Utilisateur(
                nom=fake.name(),
                email=fake.unique.email(),
                mot_de_passe=generate_password_hash(
                    "blent"
                ),  # default test password
                role=random.choice(["client", "client", "admin"]),
                date_creation=fake.date_time_between(
                    start_date="-1y", end_date="now"
                ),
            )
            utilisateurs.append(user)
            db.session.add(user)

        # 2. Generate Products with Realistic IT Names
        print("Generating products...")
        # Custom dictionary to ensure names like "ASUS NVIDIA RTX 4080"
        # instead of generic text
        DATA_INFO = {
            "Processeur": [
                "Intel Core i9",
                "AMD Ryzen 7",
                "Intel Core i5",
                "Apple M2",
            ],
            "Carte Graphique": [
                "NVIDIA RTX 4080",
                "AMD Radeon RX 7900",
                "NVIDIA GTX 1650",
            ],
            "Stockage": [
                "SSD NVMe 1To",
                "Disque Dur 4To",
                "SSD Externe USB-C",
            ],
            "Mémoire RAM": [
                "DDR5 32Go",
                "DDR4 16Go 3200MHz",
                "Kit Dual Channel 64Go",
            ],
            "Écran": [
                'Moniteur 27" 4K',
                "Dalle OLED 144Hz",
                'Écran Incurvé 34"',
            ],
            "Accessoire": [
                "Clavier Mécanique RGB",
                "Souris Sans Fil",
                "Casque Audio 7.1",
            ],
        }

        produits = []
        for _ in range(NUM_RECORDS):
            # Select a random category and item from the list above
            cat_info = random.choice(list(DATA_INFO.keys()))
            brand = random.choice(
                ["ASUS", "MSI", "Corsair", "Logitech", "Samsung", "Gigabyte"]
            )
            model = random.choice(DATA_INFO[cat_info])

            # Generate a random description using Faker's paragraph generator
            prod_desc = f"{fake.paragraph(nb_sentences=3)}"

            # Create the product with a realistic name and description
            prod = Produit(
                nom=f"{brand} {model}",  # Combines brand and model for realism
                description=f"Description aléatoire: {prod_desc}",
                categorie=cat_info,
                prix=round(random.uniform(10.0, 1500.0), 2),
                quantite_stock=random.randint(0, 50),
            )
            produits.append(prod)
            db.session.add(prod)

        # Flush ensures IDs are generated by DB before related records
        db.session.flush()

        # 3. Generate Orders
        print("Generating orders...")
        commandes = []
        for _ in range(NUM_RECORDS):
            random_user = random.choice(utilisateurs)
            cmd = Commande(
                utilisateur_id=random_user.id,
                date_commande=fake.date_time_between(
                    start_date="-30d", end_date="now"
                ),
                adresse_livraison=fake.address().replace("\n", " "),
                statut=random.choice(
                    ["en_attente", "validée", "expédiée", "annulée"]
                ),
            )
            commandes.append(cmd)
            db.session.add(cmd)

        # Flush to get Order IDs for the line items
        db.session.flush()  # < commit

        # 4. Generate Order Line Items (Items inside the orders)
        print("Generating order line items...")
        for _ in range(NUM_RECORDS * 2):
            random_cmd = random.choice(commandes)
            random_prod = random.choice(produits)

            line = LigneCommande(
                commande_id=random_cmd.id,
                produit_id=random_prod.id,
                quantite=random.randint(1, 5),
                prix_unitaire=random_prod.prix,
            )
            db.session.add(line)

        # Final commit to save everything to the database file
        db.session.commit()
        print("Database successfully populated!")


if __name__ == "__main__":
    seed_database()
